version: '3.8'

services:
  telegram-obs-overlay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-obs-overlay-dev
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - PORT=${PORT:-3000}
      - NODE_ENV=development
    command: nodemon server.js
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
            - .git/
            - .env
            - .env.example
            - .gitignore
            - .dockerignore
            - Dockerfile
            - docker-compose*.yml
        - action: rebuild
          path: package.json 